### ISSUE TITLE
Samsung galaxy tab s8 and s9 devices are not recognised

### ISSUE THREAD

**Issue by JDWaghela** [faisalman/ua-parser-js#740]
**Library version**
0.7.30

**Describe the bug**
Samsung Galaxy Tab s8 and s9 are returning empty object in below code
const { device } = UAParser();
Therefore we're not able to identified that these devices are tablet, and instead it is behaving like desktop mode.

**To Reproduce**

const { device } = UAParser();
console.log(device); // resulting output is {}

**Expected behavior**
It should return device type as tablet

**Screenshots**
![image](https://github.com/user-attachments/assets/bdae6692-860d-4a4f-8d8a-f68754eb25ca)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tablet s8 & s9
 - OS: Android
 - Browser : Chrome

**Comment by faisalman** [comment]
Hi, can I get a confirmation of the detection result from https://uaparser.dev/?

**Comment by JDWaghela** [comment]
> https://uaparser.dev/

@faisalman Please find below response from that site in tablets

Samsung Galaxy Tablet S8
```yaml
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "123.0.6312.40",
    "major": "123"
  },
  "cpu": {
    "architecture": "amd64"
  },
  "device": {},
  "engine": {
    "name": "Blink",
    "version": "123.0.0.0"
  },
  "os": {
    "name": "Linux",
    "version": ""
  }
}
```
Samsung Galaxy Tablet S9
```yaml
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "127.0.6533.64",
    "major": "127"
  },
  "cpu": {
    "architecture": "amd64"
  },
  "device": {},
  "engine": {
    "name": "Blink",
    "version": "127.0.0.0"
  },
  "os": {
    "name": "Linux",
    "version": ""
  }
}
```
